name: trivy-fs

on:
  push:
    branches: [main]

jobs:
  analyze:
    name: Vulnerability Scan repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: tree
        run: tree
