name: trivy

on:
  push:
    branches: [main]

jobs:
  analyze:
    name: Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Check app template
        run: docker run --rm -v ${{ github.workspace }}:/project -w /project public.ecr.aws/aquasecurity/trivy:0.21.0 conf --severity HIGH app/

      - name: Check .devcontainer Dockerfile
        run: docker run --rm -v ${{ github.workspace }}:/project -w /project public.ecr.aws/aquasecurity/trivy:0.21.0 conf --severity HIGH .devcontainer/

      - name: Check application files
        run: docker run --rm -v ${{ github.workspace }}:/project -w /project public.ecr.aws/aquasecurity/trivy:0.21.0 fs --severity HIGH app/

      - name: Check rootfs
        run: docker run --rm -v ${{ github.workspace }}:/project -w /project public.ecr.aws/aquasecurity/trivy:0.21.0 rootfs --severity HIGH app/

      - name: Build devcontainer
        run: docker build -t devcon:latest .
        working-directory: .devcontainer

      - name: Check devcontainer image
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock public.ecr.aws/aquasecurity/trivy:0.21.0 image --severity HIGH devcon:latest
