name: trivy-conf

on:
  push:
    branches: [main]

jobs:
  analyze:
    name: Vulnerability Scan IaC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run Trivy vulnerability scanner in IaC mode
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace public.ecr.aws/aquasecurity/trivy:0.21.0 config --format template --template @/contrib/sarif.tpl --severity CRITICAL,HIGH --output trivy-results.sarif .

      - name: Upload Trivy IaC scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
